In [16]:
import numpy as np
from scipy.linalg import *
import matplotlib as plt

In [53]:
#Definição das propriedades e mesh

ka = 10 #W/m°C 
kb = 1 #W/m°C
La = 0.073 #m
Lb = 0.017 #m
h = 80 ##W/m²°C
T_infinito = 20 #°C
q0 = 4000 #W/m²
A = 1 #m²; área transversal hipotética
q_ponto = 0 #problema sem geração



meshA = 5
meshB = 3

Matrix_coef_a = np.zeros((meshA+meshB,meshA+meshB))
Matrix_coef_b = np.zeros((meshA+meshB,1))

deltax_A = La/(meshA-0.5)
deltax_B = Lb/(meshB-0.5)


In [54]:
#ke por interpolação linear

for volume in range(meshA):
    if (volume == 0):
        ae = ka*A/(deltax_A/2)
        ap = ae
        b = q_ponto*A*deltax_A/2 + q0*A
        
        Matrix_coef_a[volume,volume] = ap
        Matrix_coef_a[volume,volume+1] = -ae
        Matrix_coef_b[volume] = b
        
    if (volume != 0) and (volume != meshA-1):
        ae = ka*A/(deltax_A)
        aw = ae
        ap = ae + aw
        b = q_ponto*A*deltax_A
        
        Matrix_coef_a[volume,volume] = ap
        Matrix_coef_a[volume,volume+1] = -ae
        Matrix_coef_a[volume,volume-1] = -aw
        Matrix_coef_b[volume] = b
        
    if (volume == meshA-1):
        fe = deltax_A/(deltax_A+deltax_B)  #verificar
        ke = fe*ka + (1-fe)*kb
        
        ae = ke*A/((deltax_A+deltax_B)/2)
        aw = ka*A/(deltax_A)
        ap = ae + aw
        b = q_ponto*A*deltax_A
        
        Matrix_coef_a[volume,volume] = ap
        Matrix_coef_a[volume,volume+1] = -ae
        Matrix_coef_a[volume,volume-1] = -aw
        Matrix_coef_b[volume] = b
        
        
for volume in range(meshB):
    if (volume == 0):
        fw = deltax_A/(deltax_A+deltax_B)  #verificar
        kw = fw*ka + (1-fw)*kb
        
        aw = kw*A/((deltax_A+deltax_B)/2)
        ae = kb*A/(deltax_B)
        ap = ae + aw
        b = q_ponto*A*deltax_B
        
        Matrix_coef_a[meshA + volume,meshA + volume] = ap
        Matrix_coef_a[meshA + volume,meshA + volume+1] = -ae
        Matrix_coef_a[meshA + volume,meshA + volume-1] = -aw
        Matrix_coef_b[meshA + volume] = b
        
        
    if (volume != 0) and (volume != meshB-1):
        ae = kb*A/(deltax_B)
        aw = ae
        ap = ae + aw
        b = q_ponto*A*deltax_B
        
        Matrix_coef_a[meshA + volume,meshA + volume] = ap
        Matrix_coef_a[meshA + volume,meshA + volume+1] = -ae
        Matrix_coef_a[meshA + volume,meshA + volume-1] = -aw
        Matrix_coef_b[meshA + volume] = b
        
        
    if (volume == meshB-1):
        aw = kb*A/(deltax_B)
        aw_f = h*A
        ap = aw + aw_f
        b = q_ponto*A*deltax_B +aw_f * T_infinito
        
        Matrix_coef_a[meshA + volume,meshA + volume] = ap
        Matrix_coef_a[meshA + volume,meshA + volume-1] = -aw
        Matrix_coef_b[meshA + volume] = b
        
        
T_interpolacao = solve(Matrix_coef_a,Matrix_coef_b)
        


In [55]:
Matrix_coef_a

array([[ 1232.87671233, -1232.87671233,     0.        ,     0.        ,
            0.        ,     0.        ,     0.        ,     0.        ],
       [ -616.43835616,  1232.87671233,  -616.43835616,     0.        ,
            0.        ,     0.        ,     0.        ,     0.        ],
       [    0.        ,  -616.43835616,  1232.87671233,  -616.43835616,
            0.        ,     0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,  -616.43835616,  1232.87671233,
         -616.43835616,     0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ,  -616.43835616,
         1254.23072658,  -637.79237042,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ,     0.        ,
         -637.79237042,   784.85119395,  -147.05882353,     0.        ],
       [    0.        ,     0.        ,     0.        ,     0.        ,
            0.        ,  -147.05882353,   294.11764706,  -

In [56]:
Matrix_coef_b

array([[ 4000.],
       [    0.],
       [    0.],
       [    0.],
       [    0.],
       [    0.],
       [    0.],
       [ 1600.]])

In [57]:
T_interpolacao

array([[ 88.31359453],
       [ 85.06915009],
       [ 81.82470564],
       [ 78.5802612 ],
       [ 75.33581675],
       [ 72.2       ],
       [ 58.6       ],
       [ 45.        ]])